### ISSUE TITLE
I cloned your repo and attach the external usb camera, but it's not working 

### ISSUE THREAD

**Issue by MrAdi149** [shanerodrigues/compose-uvc-camera#3]
i got this message in logcat can you help me:
2024-07-03 15:20:54.844 13334-13590 CameraUvc               com.example.camerauvctest            E  Find no uvc devices, if you want some special device please use getUsbDeviceList() or add device info into default_device_filter.xml

**Comment by shanerodrigues** [comment]
Hi @MrAdi149, sorry, I don't have access to any USB cameras so I can't replicate the error you're getting. Perhaps see if you can try using the original library [AndroidUSBCamera by jiangdongguo](https://github.com/jiangdongguo/AndroidUSBCamera).

**Comment by MrAdi149** [comment]
Thank you for your response, @shanerodrigues . I tried the original library, but it didn't work. Could you recommend another similar library? That would be very helpful.
